### ISSUE TITLE
It is possible to put a link to this project in https://github.com/joscha/play-authenticate?

### ISSUE THREAD

**Issue by 030** [bravegag/play-authenticate-usage-scala#6]
Or to merge it in https://github.com/joscha/play-authenticate

and to mention that 

if There is no HTTP Context available from here occurs

this could be caused as java and scala will not work in this case

https://groups.google.com/forum/#!topic/play-framework/PoQajClVx_8

**Comment by bravegag** [comment]
Hi, sure please add a link :+1:. I would also consider merging it .. however, since the purpose of this project is to have a clean pure Scala bare-bone for my Web App projects I think it will have its own speed of development rather than then having to wait for others in regards to releases/ merges etc.
